import Link from 'next/link'
import styles from './legal.module.css'

export default function TermsPage() {
  return (
    <div className={styles.page}>
      <nav className="nav">
        <div className="container">
          <div className="nav-content">
            <Link href="/" className="nav-logo">IncDigest</Link>
            <div className="nav-links">
              <Link href="/blog">Blog</Link>
              <Link href="/pricing">Pricing</Link>
              <Link href="/login">Login</Link>
            </div>
          </div>
        </div>
      </nav>

      <main className={styles.main}>
        <div className="container-narrow">
          <h1>Terms and Conditions</h1>
          <p className={styles.lastUpdated}>Last Updated: February 4, 2026</p>

          <div className={styles.content}>
            <p className={styles.warning}>
              <strong>PLEASE READ THESE TERMS CAREFULLY BEFORE USING INCDIGEST</strong>
            </p>
            
            <p>
              By accessing or using IncDigest ("the Service"), you agree to be bound by these Terms and Conditions ("Terms"). 
              If you do not agree to these Terms, do not use the Service.
            </p>

            <h2>1. Acceptance of Terms</h2>
            <p>
              By creating an account, purchasing tokens, or generating reports through IncDigest, you acknowledge that you 
              have read, understood, and agree to be bound by these Terms and all applicable laws and regulations.
            </p>

            <h2>2. Description of Service</h2>
            <p>IncDigest is an artificial intelligence-powered analysis platform that generates summaries comparing annual SEC filings. The Service:</p>
            <ul>
              <li>Uses AI to identify and summarize material changes between consecutive filings</li>
              <li>Focuses on relevant sections of such documents</li>
              <li>Provides automated analysis for informational and research purposes only</li>
            </ul>

            <h2>3. NOT INVESTMENT ADVICE - CRITICAL DISCLAIMER</h2>
            <div className={styles.criticalWarning}>
              <p><strong>THE SERVICE DOES NOT PROVIDE INVESTMENT, FINANCIAL, LEGAL, OR TAX ADVICE.</strong></p>
              <ul>
                <li>All reports, summaries, and analyses generated by IncDigest are <strong>for informational purposes only</strong></li>
                <li>Content is <strong>AI-generated</strong> and may contain errors, omissions, or inaccuracies</li>
                <li><strong>You should not</strong> make investment decisions based solely on IncDigest reports</li>
                <li><strong>You must</strong> conduct your own due diligence and consult with qualified financial, legal, and tax professionals before making any investment decisions</li>
                <li>Past performance of any security does not guarantee future results</li>
                <li>All investments carry risk, including the potential loss of principal</li>
              </ul>
              
              <p>IncDigest and its operators:</p>
              <ul>
                <li>Are <strong>not</strong> registered investment advisors</li>
                <li>Do <strong>not</strong> recommend buying, selling, or holding any securities</li>
                <li>Make <strong>no representations</strong> about the suitability of any investment</li>
                <li>Accept <strong>no responsibility</strong> for investment decisions you make</li>
              </ul>
            </div>

            <h2>4. AI-Generated Content Limitations</h2>
            <p><strong>YOU ACKNOWLEDGE AND AGREE:</strong></p>
            <ul>
              <li>Reports are generated by artificial intelligence (Claude Sonnet 4 by Anthropic)</li>
              <li>AI may produce errors, hallucinations, or incorrect interpretations</li>
              <li>We make <strong>no guarantee</strong> of accuracy, completeness, or reliability</li>
              <li>AI may miss material changes or misinterpret SEC filings</li>
              <li>Technology limitations may affect output quality</li>
              <li>Results may vary between similar queries</li>
              <li>The Service is a tool to assist research, not replace human judgment</li>
            </ul>

            <p><strong>YOU ARE SOLELY RESPONSIBLE FOR:</strong></p>
            <ul>
              <li>Verifying all information in generated reports</li>
              <li>Reading original SEC filings yourself</li>
              <li>Making your own independent assessments</li>
              <li>Any decisions based on Service output</li>
            </ul>

            <h2>5. Account Registration and Security</h2>
            <p><strong>You agree to:</strong></p>
            <ul>
              <li>Provide accurate, current, and complete information during registration</li>
              <li>Maintain the security of your password and account</li>
              <li>Notify us immediately of unauthorized use</li>
              <li>Accept responsibility for all activities under your account</li>
            </ul>

            <p><strong>We reserve the right to:</strong></p>
            <ul>
              <li>Refuse service to anyone for any reason</li>
              <li>Terminate accounts that violate these Terms</li>
              <li>Require additional verification of identity</li>
            </ul>

            <h2>6. Token System and Pricing</h2>
            <p><strong>Payment and Tokens:</strong></p>
            <ul>
              <li>Reports are purchased using tokens at $1.00 USD per token/report</li>
              <li>Token packages: 10 tokens ($10), 50 tokens ($45), 200 tokens ($160)</li>
              <li>Tokens are non-refundable except as specified in Section 7</li>
              <li>Tokens expire twenty four months after purchase</li>
              <li>Pricing subject to change with 30 days notice to existing users</li>
            </ul>

            <p><strong>One Token = One Report</strong></p>
            <ul>
              <li>Each report generation costs one (1) token</li>
              <li>Tokens are deducted when report generation begins</li>
            </ul>

            <h2>7. Refund Policy</h2>
            <p><strong>Automatic Refunds:</strong></p>
            <p>Tokens are <strong>automatically refunded</strong> if:</p>
            <ul>
              <li>Report generation fails due to technical error</li>
              <li>Company has insufficient filings available</li>
              <li>Company is not a U.S. company (files 20-F or 40-F instead)</li>
              <li>Service cannot extract required sections</li>
              <li>AI analysis fails to complete</li>
            </ul>

            <p><strong>No Refunds For:</strong></p>
            <ul>
              <li>User dissatisfaction with report content or quality</li>
              <li>Reports that complete successfully but don't meet user expectations</li>
              <li>Misunderstanding of what the Service provides</li>
              <li>Changes in investment decisions or market conditions</li>
              <li>User error in ticker selection</li>
              <li>Reports the user decides they didn't need after generation</li>
            </ul>

            <p><strong>Dispute Resolution:</strong></p>
            <p>If you believe a report contains objectively incorrect information (factual errors, wrong company, wrong filings), contact support@incdigest.com within 7 days. We will:</p>
            <ol>
              <li>Review the report and original SEC filings</li>
              <li>Verify if an objective error occurred</li>
              <li>Issue a refund if error is confirmed</li>
              <li>Update our systems to prevent similar errors</li>
            </ol>
            <p>Subjective quality assessments ("not detailed enough", "didn't highlight what I wanted") are not grounds for refunds.</p>

            <h2>8. Intellectual Property</h2>
            <p><strong>Our Content:</strong></p>
            <ul>
              <li>The Service, including software, algorithms, design, and branding, is owned by IncDigest</li>
              <li>SEC filings are public domain documents published by the U.S. Securities and Exchange Commission</li>
              <li>AI summaries are generated automatically based on your ticker selection</li>
            </ul>

            <p><strong>Your Rights:</strong></p>
            <ul>
              <li>You may use generated reports for personal research and analysis</li>
              <li>You may not resell, redistribute, or republish IncDigest reports commercially</li>
              <li>You may not reverse engineer or replicate the Service</li>
              <li>You may share reports internally within your organization</li>
            </ul>

            <h2>9. User Conduct</h2>
            <p><strong>You agree NOT to:</strong></p>
            <ul>
              <li>Use the Service for illegal purposes</li>
              <li>Attempt to gain unauthorized access to systems</li>
              <li>Interfere with or disrupt the Service</li>
              <li>Use automated systems (bots, scrapers) without permission</li>
              <li>Violate securities laws or regulations</li>
              <li>Manipulate markets using Service information</li>
              <li>Impersonate others or provide false information</li>
              <li>Upload malware, viruses, or harmful code</li>
            </ul>

            <h2>10. Data Collection and Privacy</h2>
            <p><strong>We collect:</strong></p>
            <ul>
              <li>Account information (email, password)</li>
              <li>Usage data (reports generated, tickers searched)</li>
              <li>Payment information (processed by Stripe, not stored by us)</li>
              <li>Authentication data (session tokens, 2FA if enabled)</li>
            </ul>

            <p><strong>We use data to:</strong></p>
            <ul>
              <li>Provide and improve the Service</li>
              <li>Process payments and maintain accounts</li>
              <li>Send service-related communications</li>
              <li>Prevent fraud and abuse</li>
            </ul>

            <p>See our <Link href="/privacy">Privacy Policy</Link> for complete details.</p>

            <h2>11. Third-Party Services</h2>
            <p>The Service integrates with:</p>
            <ul>
              <li><strong>Stripe</strong> for payment processing</li>
              <li><strong>Anthropic Claude</strong> for AI analysis</li>
              <li><strong>SEC EDGAR</strong> for filing retrieval</li>
              <li><strong>Supabase</strong> for data storage</li>
              <li><strong>Railway</strong> for Python functions</li>
            </ul>
            <p>You agree to comply with third-party terms. We are not responsible for third-party service failures or changes.</p>

            <h2>12. Service Availability and Modifications</h2>
            <p><strong>We reserve the right to:</strong></p>
            <ul>
              <li>Modify, suspend, or discontinue any feature</li>
              <li>Change pricing with 30 days notice</li>
              <li>Perform maintenance that temporarily interrupts service</li>
              <li>Update AI models or analysis methods</li>
              <li>Remove or restrict access to certain companies or filings</li>
            </ul>

            <p><strong>We are not liable for:</strong></p>
            <ul>
              <li>Service interruptions or downtime</li>
              <li>Data loss or corruption</li>
              <li>Changes to third-party APIs</li>
              <li>SEC filing availability or format changes</li>
            </ul>

            <h2>13. Limitation of Liability</h2>
            <div className={styles.criticalWarning}>
              <p><strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</strong></p>
              <p>IncDigest and its operators, employees, and affiliates SHALL NOT BE LIABLE for:</p>
              <ul>
                <li>Investment losses or financial damages</li>
                <li>Lost profits or business opportunities</li>
                <li>Indirect, incidental, or consequential damages</li>
                <li>Damages resulting from Service errors or inaccuracies</li>
                <li>Damages from unauthorized access to your account</li>
                <li>Damages from reliance on AI-generated content</li>
              </ul>

              <p><strong>TOTAL LIABILITY</strong> for any claim shall not exceed the amount you paid for tokens in the 12 months preceding the claim.</p>

              <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.</p>
            </div>

            <h2>14. Indemnification</h2>
            <p>You agree to indemnify and hold harmless IncDigest, its operators, employees, and affiliates from any claims, damages, losses, or expenses (including legal fees) arising from:</p>
            <ul>
              <li>Your use of the Service</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of applicable laws or regulations</li>
              <li>Investment decisions you make</li>
              <li>Your breach of securities laws</li>
            </ul>

            <h2>15. Governing Law and Disputes</h2>
            <p>These Terms are governed by the laws of England and Wales, without regard to conflict of law provisions.</p>
            
            <p><strong>Dispute Resolution:</strong></p>
            <ol>
              <li>Contact support@incdigest.com to resolve informally</li>
              <li>If unresolved, disputes shall be settled by binding arbitration in accordance with UK arbitration rules</li>
              <li>You waive the right to participate in class action lawsuits</li>
            </ol>

            <h2>16. Termination</h2>
            <p><strong>We may terminate your access if you:</strong></p>
            <ul>
              <li>Violate these Terms</li>
              <li>Engage in fraudulent activity</li>
              <li>Abuse the Service or other users</li>
              <li>Fail to pay for services</li>
            </ul>

            <p><strong>Upon termination:</strong></p>
            <ul>
              <li>Your access to the Service ends immediately</li>
              <li>Unused tokens are forfeited (no refund)</li>
              <li>Generated reports may be deleted</li>
              <li>These Terms survive termination where applicable</li>
            </ul>

            <p><strong>You may terminate by:</strong></p>
            <ul>
              <li>Deleting your account through the dashboard</li>
              <li>Contacting support@incdigest.com</li>
              <li>Unused tokens are forfeited upon voluntary termination</li>
            </ul>

            <h2>17. Severability</h2>
            <p>If any provision of these Terms is found invalid or unenforceable, the remaining provisions shall remain in full effect.</p>

            <h2>18. Entire Agreement</h2>
            <p>These Terms, together with our Privacy Policy, constitute the entire agreement between you and IncDigest regarding the Service.</p>

            <h2>19. Changes to Terms</h2>
            <p>We may update these Terms at any time. Changes will be posted with a new "Last Updated" date. Continued use after changes constitutes acceptance. Material changes will be notified via email.</p>

            <h2>20. Contact Information</h2>
            <p>For questions about these Terms:</p>
            <ul>
              <li>Email: support@incdigest.com</li>
              <li>Website: https://incdigest.com/contact</li>
            </ul>

            <h2>21. Acknowledgment</h2>
            <div className={styles.criticalWarning}>
              <p><strong>BY USING INCDIGEST, YOU ACKNOWLEDGE:</strong></p>
              <ul>
                <li>You have read and understood these Terms in full</li>
                <li>You accept all risks associated with using AI-generated investment research</li>
                <li>You will not rely solely on IncDigest for investment decisions</li>
                <li>You understand the Service does not provide investment advice</li>
                <li>You are solely responsible for your investment decisions and their outcomes</li>
                <li>You will consult qualified professionals before making investment decisions</li>
              </ul>
            </div>
          </div>

          <div className={styles.footer}>
            <p className="text-secondary text-sm">Last Updated: February 4, 2026</p>
            <p className="text-secondary text-sm">© 2026 IncDigest. All rights reserved.</p>
          </div>
        </div>
      </main>
    </div>
  )
}
